spring:
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  profiles:
    active:
      - ${SPRING_ACTIVE_PROFILE}
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names:
      - channels
      - notifications
      - users
    caffeine:
      spec: recordStats
    redis:
      enable-statistics: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: discodeit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,caches
  endpoint:
    health:
      show-details: always
  observations:
    annotations:
      enabled: true

info:
  name: Discodeit
  version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.maxFileSize}
      max-request-size: ${spring.servlet.multipart.maxRequestSize}

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}  # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)
  security:
    remember-me-secret: ${REMEMBER_ME_SECRET}
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}
  jwt:
    #    issuer: ${JWT_ISSUER}
    access-token:
      secret: ${JWT_ACCESS_TOKEN_SECRET}
      expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS}
    refresh-token:
      secret: ${JWT_REFRESH_TOKEN_SECRET}
      expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS}

logging:
  level:
    root: info

server:
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: 5m
      tracking-modes: cookie


